### ISSUE TITLE
poetry install breaks while installing sphinx-bootstrap-theme

### ISSUE THREAD

**Issue by Legotier** [Philipp15b/probably#1]
Since version 58 of the `setuptools` package, the [2to3 functionality is no longer supported](https://setuptools.pypa.io/en/latest/history.html#v58-0-0). This means that calling `poetry install` will fail while installing the `sphinx-bootstrap-theme`-package. 

A solution that works is to downgrade `setuptools` to an earlier version, e.g. by calling `poetry run pip install setuptools==57.5.0` prior to `poetry install`. However, this should probably be automated if possible.

This is on the `forward`-branch; I don't know if the problem exists on other branches as well.

**Comment by LKlinke** [comment]
@Philipp15b I tired updating it to 0.8.1 and the issue vanishes.
